concurrent = 1
check_interval = 0

[[runners]]
  name = "bb4db9d95608"
  url = "https://gitlab.com/"
  token = "4def5f4c450553a3bf6a2f25a58176"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
